"use client"
import { useDispatch, useSelector } from "react-redux";
import {insertar} from "./regionSlice"
import {integracion} from "./Integracion"



export const cities = [
  { name: "Kabul", country: "Afghanistan" },
  { name: "Tirana", country: "Albania" },
  { name: "Algiers", country: "Algeria" },
  { name: "Andorra la Vella", country: "Andorra" },
  { name: "Luanda", country: "Angola" },
  { name: "Saint John's", country: "Antigua and Barbuda" },
  { name: "Buenos Aires", country: "Argentina" },
  { name: "Yerevan", country: "Armenia" },
  { name: "Canberra", country: "Australia" },
  { name: "Vienna", country: "Austria" },
  { name: "Baku", country: "Azerbaijan" },
  { name: "Nassau", country: "Bahamas" },
  { name: "Manama", country: "Bahrain" },
  { name: "Dhaka", country: "Bangladesh" },
  { name: "Bridgetown", country: "Barbados" },
  { name: "Minsk", country: "Belarus" },
  { name: "Brussels", country: "Belgium" },
  { name: "Belmopan", country: "Belize" },
  { name: "Porto-Novo", country: "Benin" },
  { name: "Thimphu", country: "Bhutan" },
  { name: "La Paz", country: "Bolivia" },
  { name: "Sarajevo", country: "Bosnia and Herzegovina" },
  { name: "Gaborone", country: "Botswana" },
  { name: "Brasília", country: "Brazil" },
  { name: "Bandar Seri Begawan", country: "Brunei" },
  { name: "Sofia", country: "Bulgaria" },
  { name: "Ouagadougou", country: "Burkina Faso" },
  { name: "Gitega", country: "Burundi" },
  { name: "Phnom Penh", country: "Cambodia" },
  { name: "Yaoundé", country: "Cameroon" },
  { name: "Ottawa", country: "Canada" },
  { name: "Praia", country: "Cape Verde" },
  { name: "Bangui", country: "Central African Republic" },
  { name: "N'Djamena", country: "Chad" },
  { name: "Santiago", country: "Chile" },
  { name: "Beijing", country: "China" },
  { name: "Bogotá", country: "Colombia" },
  { name: "Moroni", country: "Comoros" },
  { name: "Kinshasa", country: "Congo (Democratic Republic)" },
  { name: "Brazzaville", country: "Congo (Republic)" },
  { name: "San José", country: "Costa Rica" },
  { name: "Zagreb", country: "Croatia" },
  { name: "Havana", country: "Cuba" },
  { name: "Nicosia", country: "Cyprus" },
  { name: "Prague", country: "Czech Republic" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Djibouti", country: "Djibouti" },
  { name: "Roseau", country: "Dominica" },
  { name: "Santo Domingo", country: "Dominican Republic" },
  { name: "Quito", country: "Ecuador" },
  { name: "Cairo", country: "Egypt" },
  { name: "San Salvador", country: "El Salvador" },
  { name: "Malabo", country: "Equatorial Guinea" },
  { name: "Asmara", country: "Eritrea" },
  { name: "Tallinn", country: "Estonia" },
  { name: "Eswatini", country: "Mbabane" },
  { name: "Addis Ababa", country: "Ethiopia" },
  { name: "Suva", country: "Fiji" },
  { name: "Helsinki", country: "Finland" },
  { name: "Paris", country: "France" },
  { name: "Libreville", country: "Gabon" },
  { name: "Banjul", country: "Gambia" },
  { name: "Tbilisi", country: "Georgia" },
  { name: "Berlin", country: "Germany" },
  { name: "Accra", country: "Ghana" },
  { name: "Athens", country: "Greece" },
  { name: "Saint George's", country: "Grenada" },
  { name: "Guatemala City", country: "Guatemala" },
  { name: "Conakry", country: "Guinea" },
  { name: "Bissau", country: "Guinea-Bissau" },
  { name: "Georgetown", country: "Guyana" },
  { name: "Port-au-Prince", country: "Haiti" },
  { name: "Tegucigalpa", country: "Honduras" },
  { name: "Budapest", country: "Hungary" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "New Delhi", country: "India" },
  { name: "Jakarta", country: "Indonesia" },
  { name: "Tehran", country: "Iran" },
  { name: "Baghdad", country: "Iraq" },
  { name: "Dublin", country: "Ireland" },
  { name: "Jerusalem", country: "Israel" },
  { name: "Rome", country: "Italy" },
  { name: "Kingston", country: "Jamaica" },
  { name: "Tokyo", country: "Japan" },
  { name: "Amman", country: "Jordan" },
  { name: "Astana", country: "Kazakhstan" },
  { name: "Nairobi", country: "Kenya" },
  { name: "Tarawa", country: "Kiribati" },
  { name: "Pristina", country: "Kosovo" },
  { name: "Kuwait City", country: "Kuwait" },
  { name: "Bishkek", country: "Kyrgyzstan" },
  { name: "Vientiane", country: "Laos" },
  { name: "Riga", country: "Latvia" },
  { name: "Beirut", country: "Lebanon" },
  { name: "Maseru", country: "Lesotho" },
  { name: "Monrovia", country: "Liberia" },
  { name: "Tripoli", country: "Libya" },
  { name: "Vaduz", country: "Liechtenstein" },
  { name: "Vilnius", country: "Lithuania" },
  { name: "Luxembourg", country: "Luxembourg" },
  { name: "Antananarivo", country: "Madagascar" },
  { name: "Lilongwe", country: "Malawi" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Malé", country: "Maldives" },
  { name: "Bamako", country: "Mali" },
  { name: "Valletta", country: "Malta" },
  { name: "Majuro", country: "Marshall Islands" },
  { name: "Nouakchott", country: "Mauritania" },
  { name: "Port Louis", country: "Mauritius" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Palikir", country: "Micronesia" },
  { name: "Chisinau", country: "Moldova" },
  { name: "Monaco", country: "Monaco" },
  { name: "Ulaanbaatar", country: "Mongolia" },
  { name: "Podgorica", country: "Montenegro" },
  { name: "Rabat", country: "Morocco" },
  { name: "Maputo", country: "Mozambique" },
  { name: "Naypyidaw", country: "Myanmar" },
  { name: "Windhoek", country: "Namibia" },
  { name: "Yaren", country: "Nauru" },
  { name: "Kathmandu", country: "Nepal" },
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Wellington", country: "New Zealand" },
  { name: "Managua", country: "Nicaragua" },
  { name: "Niamey", country: "Niger" },
  { name: "Abuja", country: "Nigeria" },
  { name: "Pyongyang", country: "North Korea" },
  { name: "Skopje", country: "North Macedonia" },
  { name: "Oslo", country: "Norway" },
  { name: "Muscat", country: "Oman" },
  { name: "Islamabad", country: "Pakistan" },
  { name: "Ngerulmud", country: "Palau" },
  { name: "Panama City", country: "Panama" },
  { name: "Port Moresby", country: "Papua New Guinea" },
  { name: "Asunción", country: "Paraguay" },
  { name: "Lima", country: "Peru" },
  { name: "Manila", country: "Philippines" },
  { name: "Warsaw", country: "Poland" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Doha", country: "Qatar" },
  { name: "Bucharest", country: "Romania" },
  { name: "Moscow", country: "Russia" },
  { name: "Kigali", country: "Rwanda" },
  { name: "Basseterre", country: "Saint Kitts and Nevis" },
  { name: "Castries", country: "Saint Lucia" },
  { name: "Kingstown", country: "Saint Vincent and the Grenadines" },
  { name: "Apia", country: "Samoa" },
  { name: "San Marino", country: "San Marino" },
  { name: "São Tomé", country: "São Tomé and Príncipe" },
  { name: "Riyadh", country: "Saudi Arabia" },
  { name: "Dakar", country: "Senegal" },
  { name: "Belgrade", country: "Serbia" },
  { name: "Victoria", country: "Seychelles" },
  { name: "Freetown", country: "Sierra Leone" },
  { name: "Singapore", country: "Singapore" },
  { name: "Bratislava", country: "Slovakia" },
  { name: "Ljubljana", country: "Slovenia" },
  { name: "Honiara", country: "Solomon Islands" },
  { name: "Mogadishu", country: "Somalia" },
  { name: "Pretoria", country: "South Africa" },
  { name: "Seoul", country: "South Korea" },
  { name: "Juba", country: "South Sudan" },
  { name: "Madrid", country: "Spain" },
  { name: "Colombo", country: "Sri Lanka" },
  { name: "Khartoum", country: "Sudan" },
  { name: "Paramaribo", country: "Suriname" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Bern", country: "Switzerland" },
  { name: "Damascus", country: "Syria" },
  { name: "Taipei", country: "Taiwan" },
  { name: "Dushanbe", country: "Tajikistan" },
  { name: "Dodoma", country: "Tanzania" },
  { name: "Bangkok", country: "Thailand" },
  { name: "Lomé", country: "Togo" },
  { name: "Nuku'alofa", country: "Tonga" },
  { name: "Port of Spain", country: "Trinidad and Tobago" },
  { name: "Tunis", country: "Tunisia" },
  { name: "Ankara", country: "Turkey" },
  { name: "Ashgabat", country: "Turkmenistan" },
  { name: "Funafuti", country: "Tuvalu" },
  { name: "Kampala", country: "Uganda" },
  { name: "Kyiv", country: "Ukraine" },
  { name: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "London", country: "United Kingdom" },
  { name: "Washington, D.C.", country: "United States" },
  { name: "Montevideo", country: "Uruguay" },
  { name: "Tashkent", country: "Uzbekistan" },
  { name: "Port Vila", country: "Vanuatu" },
  { name: "Vatican City", country: "Vatican City" },
  { name: "Caracas", country: "Venezuela" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Sana'a", country: "Yemen" },
  { name: "Lusaka", country: "Zambia" },
  { name: "Harare", country: "Zimbabwe" },
]; 
 
export default function Menu({focus = false, setFocus}){
    const region = useSelector(state => state.region.region)
    const dispatch = useDispatch()
    return(
<>
{region != "" &&
<div tabIndex={0} onFocus={()=>setFocus(true) } onBlur={()=>setFocus(false)} className="absolute mt-20 bg-[hsl(243,27%,20%)]   flex-col  w-[300px] h-[100px] borrounded-md overflow-scroll">
    {cities.map(e=>{
        if(region  &&  e.name.toLowerCase().startsWith(region.toLowerCase())){
            return(<h4 className="focus:scale-110" 
                onMouseDown={()=>{dispatch(insertar(e.name));integracion(dispatch,e.name);setFocus(false)}} key={e.name}>{e.name}</h4>)
            
        }else{return ""}
    })}
</div>}
            
</>)}



